import Head from "next/head";
import StyledLayout from "./style";
import { useTheme } from "../../contexts/ThemeContext";
import Header from "../Header";

const Layout = ({ children, title }) => {
  const [dark, setDark] = useTheme();
  return (
    <StyledLayout dark={dark}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <Header />
      <main>{children}</main>
    </StyledLayout>
  );
};

export default Layout;
